# Generated by Django 4.1.2 on 2022-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Book name')),
                ('author', models.CharField(max_length=100, verbose_name='Book author')),
                ('publisher', models.CharField(max_length=100, verbose_name='Book publisher')),
                ('pgnumber', models.IntegerField(verbose_name='Book pages')),
            ],
        ),
    ]
